<?php

// This file is automatically generated by Laravel...? Todo: check it (create new serviceprovider inside folder and check auto-detect?)

return [
    App\Providers\AppServiceProvider::class,
];
